# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Set Environment Variables
      env:
        REACT_APP_TEMPLATE_ID: ${{ secrets.EMAILJS_REACT_APP_TEMPLATE_ID }}
        REACT_APP_SERVICE_ID: ${{ secrets.EMAILJS_REACT_APP_SERVICE_ID }}
        REACT_APP_PUBLIC_KEY: ${{ secrets.EMAILJS_REACT_APP_PUBLIC_KEY }}
      run: |
        echo "REACT_APP_TEMPLATE_ID=${REACT_APP_TEMPLATE_ID}" >> $GITHUB_ENV
        echo "REACT_APP_SERVICE_ID=${REACT_APP_SERVICE_ID}" >> $GITHUB_ENV
        echo "REACT_APP_PUBLIC_KEY=${REACT_APP_PUBLIC_KEY}" >> $GITHUB_ENV

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: CI=false npm run build
    - run: npm test
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
